// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

/**
 *
 */
namespace DemoGameplayTags
{
// Input.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Walk);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LightAttack);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Block);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dodge);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ToggleLockOn);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ShowPlayerMenu);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ToggleHelpText);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Test1);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Test2);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Escape);

// Item.Weapon.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_NoWeapon);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Melee_OneHanded);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Melee_TwoHanded);

// Item.Armor.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor_Shield);

// Item.Consumable.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Food);

// Movement.SpeedMode.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_SpeedMode_Walk);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_SpeedMode_Jog);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_SpeedMode_Sprint);

// Settings.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Settings_Graphics);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Settings_Audio);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Settings_Audio_MuteWhenUnfocused);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Settings_Controls);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Settings_System);

// Stat.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Resource_Health);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Resource_Stamina);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Resource_Mana);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Primary_STR);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Primary_DEX);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Primary_INT);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Derived_Attack);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Derived_Defense);

// Character states: State.[state]
// These can also be used as action tags.
// MUST sync with UStateManagerComponent::UStateManagerComponent() - std::call_once - AllStates
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_General);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Disabled);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Jump);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ToggleCombat);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodge);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Block);

// Character actions: State.[state].[action]
// *.[subaction] is not allowed for now.
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ToggleCombat_Enter);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ToggleCombat_Exit);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_Light);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_Heavy);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_Charged);

// StateTree.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Tree_Main);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Event_TargetLost);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Event_TargetSensed);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTree_Event_Death);

// UI.Action.Item.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Action_Item_Use);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Action_Item_Drop);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Action_Item_Unequip);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Action_Item_Cancel);

// UI.PlayerMenu.*
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_PlayerMenu_Stats);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_PlayerMenu_Inventory);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_PlayerMenu_Equipment);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_PlayerMenu_Settings);
DEMO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_PlayerMenu_SystemMenu);
} // namespace DemoGameplayTags